COGNITIVE_SERVICES_KEY=""
PERSON_GROUP_ID=""
SCREEN_ID=""
FIREBASE_CONFIG = {
    "apiKey": "",
    "authDomain": "",
    "databaseURL": "",
    "storageBucket": ""
}
MIFARE_API_LOGIN=""
MIFARE_API_PASSWORD=""
MIFARE_API_URL=""
STUDENT_API_LOGIN=""
STUDENT_API_PASSWORD=""
STUDENT_API_URL=""
